UserIterface/Controllers/GameController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using BlackJack.ViewModels.GameViewModel;
using BlackJack.ViewModels.GameViewModel.Enum;
using BusinessLogic;
using BusinessLogic.Interfaces;

namespace UserIterface.Controllers
{
    public class GameController : Controller
    {
        #region references
        private readonly IGameService _gameService;
        private readonly IMappingService _mappingService;
        public GameController(IGameService gameService, IMappingService mappingService)
        {
            _mappingService = mappingService;
            _gameService = gameService;
        }
        #endregion

        public async Task<ActionResult> Start()
        {
            var allHumanPlayer = await _gameService.SelectAllHumanPlayers();
            return View(allHumanPlayer);
        }

        [HttpGet]
        public async Task<ActionResult> CurrentGame(int gameId)
        {
            try
            {
                var startGame = await _gameService.CreateFirstRoundForAllPlayers(gameId);
                if (startGame.CheckEndGame == GameEndView.EndGame)
                {
                    return RedirectToAction("EndGame", "Game", new { gameId = startGame.GameId });
                }
                return View(startGame);
            }
            catch (Exception e)
            {
                ErrorGameView errorGameView = new ErrorGameView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
        }

        [HttpPost]
        public async Task<ActionResult> CreateGame(string ourPlayer, int botCounts)
        {
            try
            {
                var startGame = await _gameService.CreateGame(ourPlayer, botCounts);
                return RedirectToAction("CurrentGame", "Game", new { gameId = startGame });
            }
            catch (AppValidationException e)
            {
                ErrorGameView errorGameView = new ErrorGameView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
            catch (Exception e)
            {
                ErrorGameView errorGameView = new ErrorGameView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
        }

        public async Task<ActionResult> _ViewRound(int gameId)
        {
            try
            {
                var continueGame = await _gameService.ContinueGameForPlayers(gameId);
                if (continueGame.CheckEndGame == GameEndView.ContinueGame)
                {
                    return View(continueGame);
                }
                return Json(new
                {
                    url = Url.Action("EndGame", "Game", new { gameId }),
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                ErrorGameView errorGameView = new ErrorGameView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
        }

        public async Task<ActionResult> EndGame(int gameId)
        {
            try
            {
                await _gameService.ContinueGameForDealer(gameId);
                var endGame = await _gameService.GetInformationForEndGame(gameId);
                return View(endGame);
            }
            catch (Exception e)
            {
                ErrorGameView errorGameView = new ErrorGameView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
        }
    }
}

UserIterface/Controllers/HistoryController.cs
using BlackJack.ViewModels.GameViewModel;
using BusinessLogic.Interfaces;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace UserIterface.Controllers
{
    public class HistoryController : Controller
    {
        #region references
        private readonly IHistoryService _historyService;
        public HistoryController(IHistoryService historyService)
        {
            _historyService = historyService;
        }
        #endregion

        public async Task<ActionResult> AllGames()
        {
            try
            {
                var allGames = await _historyService.SelectAllGames();
                return View(allGames);
            }
            catch (Exception e)
            {
                ErrorGameView errorGameView = new ErrorGameView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
        }

        public async Task<ActionResult> GameDetails(int id)
        {
            try
            {
                var detailsGame = await _historyService.GetDetails(id);
                return View(detailsGame);
            }
            catch (Exception e)
            {
                ErrorGameView errorGameView = new ErrorGameView();
                errorGameView.Error = e.Message;
                return View("_Error", errorGameView);
            }
        }
    }
}

UserIterface/Views/Game/CurrentGame.cshtml
@using BlackJack.GameViewModel
@model CurrentGameGameView
@{
    ViewBag.Title = "Games";
}
<div>
    <center><h4>Game # @Model.GameId.ToString()</h4></center>
    <center>
        <div id="results">
            @{
                Html.RenderPartial("_ViewRound");
            }
        </div>
        @using (Ajax.BeginForm("_ViewRound", "Game", new AjaxOptions { UpdateTargetId = "results", OnSuccess = "onSuccess", HttpMethod = "Post" }))
        {
            @Html.HiddenFor(model => Model.GameId);
            <div id="button_block">
                <button id="button_take" type="submit">Take more</button>
            </div>
        }
        <br />
        @using (Html.BeginForm("EndGame", "Game", FormMethod.Post))
        {
            @Html.HiddenFor(model => Model.GameId);
            <div id="button_block">
                <button id="button_enough" type="submit">Enough</button>
            </div>
        }
        <br />
        <br />
    </center>
</div>
@Scripts.Render("~/bundles/Game/CurrentGame")
@Scripts.Render("~/scripts/jquery-3.3.1.js")
@Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")

UserIterface/Views/Game/EndGame.cshtml
@using BlackJack.ViewModels.GameViewModel
@model EndGameGameView
@{
    ViewBag.Title = "EndGame";
}
<center><h2>End of Game</h2></center>
<center><h2>Result</h2></center>
<center>
    <table class="table1">
        <tr><th>Name </th><th>Role </th><th>Cards </th><th>Total points </th><th>Status </th></tr>
        @foreach (var players in Model.Players)
        {
            <tr>
                <td>@players.Name</td>
                <td>@players.Role.ToString()</td>
                <td>
                    @for (int i = 0; i < players.PlayerCards.Count; i++)
                    {
                        @players.PlayerCards[i].Name<text></text> @players.PlayerCards[i].Suit<text></text> @players.PlayerCards[i].Value
                        <br />
                    }
                </td>
                <td>
                    @players.CardSum.ToString()
                </td>
                <td>
                    @players.Result.ToString()
                </td>
            </tr>
        }
        <tr>
            <td>@Model.DealerPlayer.Name</td>
            <td>@Model.DealerPlayer.Role.ToString()</td>
            <td>
                @for (int i = 0; i < @Model.DealerPlayer.PlayerCards.Count; i++)
                {
                    @Model.DealerPlayer.PlayerCards[i].Name<text></text> @Model.DealerPlayer.PlayerCards[i].Suit<text></text> @Model.DealerPlayer.PlayerCards[i].Value
                    <br />
                }
            </td>
            <td>
                @Model.DealerPlayer.CardSum.ToString()
            </td>
            <td>
                -
            </td>
        </tr>
    </table>
    <br />
    @using (Html.BeginForm("Start", "Game", FormMethod.Post))
    {
        <div id="button_block">
            <button id="button_start_new_game" type="submit">Start new game</button>
        </div>
    }
    <br />
    @using (Html.BeginForm("AllGames", "History", FormMethod.Post))
    {
        <div id="button_block">
            <button id="button_view_history" type="submit">View history</button>
        </div>
    }
</center>
@Scripts.Render("~/bundles/Game/EndGame")

UserIterface/Views/Game/Start.cshtml
@using BlackJack.ViewModels.GameViewModel
@model StartInfoGameView
@{
    List<string> HumanPLayers = new List<string>();
    foreach(var player in Model.HumanPlayers)
    {
        HumanPLayers.Add(player.Name);
    }
    ViewBag.Title = "BlackJack";
}
<center><h1>Welcome to the game</h1></center>
<center>
    <div class="startGame">
        @using (Html.BeginForm("CreateGame", "Game", FormMethod.Post))
        {
            <h4>Enter your name or select player</h4>
            <input id="ourPlayers" name="ourPlayer" />
            <h4>Choose count bot-player</h4>
            <input id="countBot" name="botCounts" />
            <h4>and start game</h4>
            <button id="button_start" type="submit">Start</button>
        }
    </div>
</center>
<script>
    var array = JSON.parse('@Newtonsoft.Json.JsonConvert.SerializeObject(HumanPLayers)'.replace(/&quot;/g, "\""));   
</script>
@Scripts.Render("~/bundles/Game/Start")

UserIterface/Views/Game/StartInfo.cshtml
@using BlackJack.ViewModels.GameViewModel
@model StartInfoGameViewModel
@{
    ViewBag.Title = "BlackJack";
    List<string> HumanPlayers = new List<string>();
    foreach (PlayerStartInfoGameViewItem p in Model.HumanPLayers)
    {
        HumanPlayers.Add(p.Name);
    }
}
<center><h1>Welcome to the game</h1></center>
<center>
    <div class="startGame">
        @using (Html.BeginForm("CurrentGame", "Game", FormMethod.Post))
        {
            <h4>Enter your name or select player</h4>
            <input id="ourPlayers" name="ourPlayers" />
            <h4>Choose count bot-player</h4>
            <input id="countBot" name="countBot" />
            <h4>and start game</h4>
            <button id="button_start" type="submit">Start</button>
        }
    </div>
</center>
<script>
    var array = JSON.parse('@Newtonsoft.Json.JsonConvert.SerializeObject(HumanPlayers)'.replace(/&quot;/g, "\""));   
</script>
@Scripts.Render("~/bundles/Game/StartInfo")

UserIterface/Views/Game/ViewRound.cshtml
@using BlackJack.GameViewModel
@model CurrentGameGameViewModel
<table class="table1">
    <tr><th>Name </th><th>Role </th><th>Cards </th><th>Total points </th><th>Status </th></tr>
    @foreach (var players in Model.PlayersList)
    {
        <tr>
            <td>@players.Name</td>
            <td>@players.Role.ToString()</td>
            <td>
                @for (int i = 0; i < players.PlayerCards.Count; i++)
                {
                    @players.PlayerCards[i].Name<text></text> @players.PlayerCards[i].Suit<text></text> @players.PlayerCards[i].Value
                    <br />
                }
            </td>
            <td>
                @players.CardSum.ToString()
            </td>
            <td>
                @players.Result.ToString()
            </td>
        </tr>
    }
    <tr>
        <td>@Model.DealerPlayer.Name</td>
        <td>@Model.DealerPlayer.Role.ToString()</td>
        <td>
            @for (int i = 0; i < @Model.DealerPlayer.PlayerCards.Count; i++)
            {
                @Model.DealerPlayer.PlayerCards[i].Name<text></text> @Model.DealerPlayer.PlayerCards[i].Suit<text></text> @Model.DealerPlayer.PlayerCards[i].Value
                <br />
            }
        </td>
        <td>
            @Model.DealerPlayer.CardSum.ToString()
        </td>
        <td>
            -
        </td>
    </tr>
</table>
<br>

UserIterface/Views/Game/_Error.cshtml
@using BlackJack.ViewModels.GameViewModel
@model ErrorGameView


<center>
    <h2>@Model.Error.ToString()</h2>
    <br />
    <img src="https://tincan.co.uk/sites/default/files/styles/banner_image_tincan/public/images/Blog-404-01.png?itok=G8jyKL7k" width="700" height="400"/>
    @using (Html.BeginForm("Start", "Game", FormMethod.Post))
    {
        <div id="button_block">
            <button id="button_start_new_game" type="submit">Try again</button>
        </div>
    }
</center>
@Scripts.Render("~/bundles/Game/Error")

UserIterface/Views/Game/_ViewRound.cshtml
@using BlackJack.GameViewModel
@model CurrentGameGameView
<table class="table1">
    <tr><th>Name </th><th>Role </th><th>Cards </th><th>Total points </th><th>Status </th></tr>
    @foreach (var players in Model.Players)
    {
        <tr>
            <td>@players.Name</td>
            <td>@players.Role.ToString()</td>
            <td>
                @for (int i = 0; i < players.PlayerCards.Count; i++)
                {
                    @players.PlayerCards[i].Name<text></text> @players.PlayerCards[i].Suit<text></text> @players.PlayerCards[i].Value
                    <br />
                }
            </td>
            <td>
                @players.CardSum.ToString()
            </td>
            <td>
                @players.Result.ToString()
            </td>
        </tr>
    }
    <tr>
        <td>@Model.DealerPlayer.Name</td>
        <td>@Model.DealerPlayer.Role.ToString()</td>
        <td>
            @for (int i = 0; i < @Model.DealerPlayer.PlayerCards.Count; i++)
            {
                @Model.DealerPlayer.PlayerCards[i].Name<text></text> @Model.DealerPlayer.PlayerCards[i].Suit<text></text> @Model.DealerPlayer.PlayerCards[i].Value
                <br />
            }
        </td>
        <td>
            @Model.DealerPlayer.CardSum.ToString()
        </td>
        <td>
            -
        </td>
    </tr>
</table>
<br>

UserIterface/Views/History/AllGames.cshtml
@using BlackJack.ViewModels.HistoryViewModel
@model AllGamesHistoryView
@{
    ViewBag.Title = "AllGames";
}
<center>
    <h2>All Games</h2>
</center>
<center>
    <div id="allGames" style="width:500px"></div>
</center>
<br />
<br />
<center>
    @using (Html.BeginForm("Start", "Game", FormMethod.Post))
    {
        <div id="button_block">
            <button id="button_start_new_game" type="submit">Start new game</button>
        </div>
    }
</center>
<script>
    var data = JSON.parse('@Newtonsoft.Json.JsonConvert.SerializeObject(Model.Games)'.replace(/&quot;/g, "\""));
</script>
@Scripts.Render("~/bundles/jquery.min")
@Scripts.Render("~/bundles/kendo.all.min")
@Scripts.Render("~/bundles/History/AllGames")

UserIterface/Views/History/GameDetails.cshtml
@using BlackJack.ViewModels.HistoryViewModel
@model GameDetailsHistoryView
@{
    ViewBag.Title = "GameDetails";
}
<center>
    <h2>Game details number @Model.GameId </h2>
</center>
<center>
    <table class="table1">
        <tr><th>Name </th><th>Role </th><th>Cards </th><th>Total points </th><th>Status </th></tr>
        @foreach (var players in Model.Players)
        {
            <tr>
                <td>@players.Name</td>
                <td>@players.Role.ToString()</td>
                <td>
                    @for (int i = 0; i < players.PlayerCards.Count; i++)
                    {
                        @players.PlayerCards[i].Name<text></text> @players.PlayerCards[i].Suit<text></text> @players.PlayerCards[i].Value
                        <br />
                    }
                </td>
                <td>
                    @players.CardSum.ToString()
                </td>
                <td>
                    @players.Result.ToString()
                </td>
            </tr>
        }
        <tr>
            <td>@Model.DealerPlayer.Name</td>
            <td>@Model.DealerPlayer.Role.ToString()</td>
            <td>
                @for (int i = 0; i < @Model.DealerPlayer.PlayerCards.Count; i++)
                {
                    @Model.DealerPlayer.PlayerCards[i].Name<text></text> @Model.DealerPlayer.PlayerCards[i].Suit<text></text> @Model.DealerPlayer.PlayerCards[i].Value
                    <br />
                }
            </td>
            <td>
                @Model.DealerPlayer.CardSum.ToString()
            </td>
            <td>
                -
            </td>
        </tr>
    </table>
    <br />
    @using (Html.BeginForm("AllGames", "History", FormMethod.Post))
    {
        <div id="button_block">
            <button id="button_view_history" type="submit">Return to history</button>
        </div>
    }
</center>
@Scripts.Render("~/bundles/History/GameDetails")

UserIterface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.2.620/styles/kendo.common-material.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2018.2.620/styles/kendo.material.mobile.min.css" />
    <script src="https://kendo.cdn.telerik.com/2018.2.620/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.2.620/js/kendo.all.min.js"></script>
    @Styles.Render("~/Content/style")
    @Styles.Render("~/Content/kendo.material.min")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Start Game", "Start", "Game", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("History Game", "AllGames", "History", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>